### PR TITLE
Update styles and layout

### PR DESCRIPTION
**Pull request by tstancheva**
Updated the css rules and the layout to improve the look and feel of the sample.

### CODE REVIEW

**Comment by AntonDobrev** [comment]
:star2:

**Comment by didiepetrova** [comment]
According to the design, it should be Cordova Plugins Samples.
Screenshot should be updated.
Cordova version should be updated.
ReadMe.md to be updated in accordance to the latest doc.

**Comment by TsvetinaIvanova** [comment]
Finished redesign and squashed commits. Waiting for approval.

**Comment by Mike4o** [comment]
:+1:

**Comment by didiepetrova** [comment]
:+1:

**Pull request merged**
